### ISSUE TITLE
Ghastly essence crashes the game. 

### ISSUE THREAD

**Issue by Gremious** [Gremious/StS-TheThiefMod#6]
```java
Exception: java.lang.NullPointerException
17:04:19.896 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.vfx.combat.FlashPowerEffect.<init>(FlashPowerEffect.java:21) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.powers.AbstractPower.flash(AbstractPower.java:424) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:269) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2552) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.
```

**Comment by Gremious** [comment]
Fixed, although Ghastly essence will be reworked #17
